@startuml
hide circle
skinparam linetype ortho
skinparam nodesep 80
skinparam ranksep 50

entity User {
  * id : INTEGER <<generated>>
  --
  telegram_id : INTEGER <<unique>>
  is_admin : BOOLEAN
}

entity Category {
  * id : INTEGER <<generated>>
  --
  name : TEXT
}

entity Lesson {
  * id : INTEGER <<generated>>
  --
  category_id : INTEGER <<FK>>
  sort_order : INTEGER <<для правильной очередности>>
  title : TEXT
  content : TEXT
}

entity UserProgress {
  * id : INTEGER <<generated>>
  --
  user_id : INTEGER <<FK>>
  lesson_id : INTEGER <<FK>>
  learned : bool
  completed_at : DATETIME
}

' Связи
Category ||--o{ Lesson
User ||--o{ UserProgress
Lesson ||--o{ UserProgress
@enduml